name: Lint and Format

on:
  push:
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install
      run: npm ci

    - name: Format
      run: npm run format

    - name: Lint
      run: npm run lint
